import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type Config = { gameDirectory?: string; suggestedDirectory?: string }; type Progress = { phase: string; percent: number; received?: number; total?: number };
function App() {
  const [config, setConfig] = useState<Config>({}); const [installed, setInstalled] = useState(false); const [progress, setProgress] = useState<Progress>(); const [message, setMessage] = useState(""); const [update, setUpdate] = useState<{ version: string; downloaded?: boolean }>(); const [busy, setBusy] = useState(false);
  const inspect = async () => { const result = await window.launcher.inspect(); setConfig({ gameDirectory: result.directory, suggestedDirectory: result.suggestedDirectory }); setInstalled(result.installed); };
  useEffect(() => { void inspect(); const removers = [window.launcher.on("install-progress", (p) => setProgress(p as Progress)), window.launcher.on("update-available", (u) => setUpdate(u as { version: string })), window.launcher.on("update-downloaded", (u) => setUpdate({ ...(u as { version: string }), downloaded: true })), window.launcher.on("game-ended", () => setMessage("Jogo encerrado.")), window.launcher.on("game-error", (e) => setMessage((e as { message: string }).message))]; return () => removers.forEach((remove) => remove()); }, []);
  const choose = async () => { const directory = await window.launcher.chooseDirectory(); if (directory) { const result = await window.launcher.setDirectory(directory); setConfig({ gameDirectory: directory }); setInstalled(result.installed); setMessage(""); } };
  const install = async () => { setBusy(true); setMessage(""); try { await window.launcher.install(); await inspect(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); setProgress(undefined); } };
  const play = async () => { setBusy(true); setMessage(""); try { await window.launcher.play(); setMessage("Jogo iniciado. Mantenha o launcher aberto."); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  return <main><header><div><small>WYD KERSEF</small><h1>Launcher</h1></div><span className="status">{installed ? "CLIENT PRONTO" : "CONFIGURAÇÃO NECESSÁRIA"}</span></header><section className="card"><h2>Arquivos do jogo</h2><p className="path">{config.gameDirectory || `Sugestão: ${config.suggestedDirectory || "escolha uma pasta"}`}</p><button onClick={() => void choose()}>Escolher pasta</button>{!installed && config.gameDirectory && <button className="primary" disabled={busy} onClick={() => void install()}>{busy ? "Instalando..." : "Baixar e instalar client"}</button>}{installed && <button className="primary" disabled={busy} onClick={() => void play()}>Jogar</button>}{progress && <div className="progress"><div style={{ width: `${progress.percent}%` }} /><span>{progress.phase === "download" ? `Baixando ${progress.percent}%` : `Extraindo ${progress.percent}%`}</span></div>}{message && <p className="message">{message}</p>}</section>{update && <section className="card update"><h2>Atualização {update.version}</h2>{update.downloaded ? <button className="primary" onClick={() => { if (confirm("Instalar agora? O jogo em execução perderá a conexão.")) void window.launcher.installUpdate(); }}>Instalar atualização</button> : <button onClick={() => void window.launcher.downloadUpdate()}>Baixar atualização</button>}</section>}<footer>O launcher mantém a conexão local ativa enquanto o jogo estiver aberto.</footer></main>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
